version: '3.8' 
services:
  maestrobot:
    build: .
    volumes:
      - .:/app
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: bash
